---
- name: Read RDS Master credentials from Secrets Manager
  ansible.builtin.command:
    argv:
      - aws
      - secretsmanager
      - get-secret-value
      - --region
      - "{{ rds_operation_aws_region }}"
      - --secret-id
      - "{{ rds_operation_master_secret_arn }}"
      - --query
      - SecretString
      - --output
      - text
  register: rds_operation_master_secret_raw
  changed_when: false
  no_log: true

- name: Parse RDS Master credentials
  ansible.builtin.set_fact:
    rds_operation_master_secret: "{{ rds_operation_master_secret_raw.stdout | from_json }}"
  no_log: true
