# 단계: poc
enable_rosa            = false
enable_ecr             = true
enable_vpn             = true
enable_rds             = true
rds_mode               = "poc"
enable_nat             = false
enable_dr_nlb          = true
enable_route53_routing = false
